<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
?>
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
Hello World<br />
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>